[package]
name = "signal-hook-shim"
version = "0.1.0"
authors = ["Jason Longshore <hello@jasonlongshore.com>"]
edition = "2018"

[lib]

[target.'cfg(unix)'.dependencies]
signal-hook = { version = "0.1.10", features = ["mio-support"] }

[target.'cfg(windows)'.dependencies]

