[package]
name = "futures"
version = "0.1.0"
authors = ["Jason Longshore <hello@jasonlongshore.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
pantomime = { path = "../../", features = ["futures-support"] }
